import type { GetServerSidePropsContext } from "next";
import Head from "next/head";
import { signIn } from "next-auth/react";

import { getServerAuthSession } from "@/server/auth";

const SignIn = () => {
  return (
    <>
      <Head>
        <title>T3 App - sign in</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container flex min-h-screen items-center justify-center gap-12 p-16">
          <div className="flex flex-col items-center gap-2">
            <button
              className="rounded-md bg-[#5865f2] px-4 py-2 text-white shadow-xl transition hover:bg-[#4752c4]"
              onClick={() => void signIn("discord")}
            >
              Continue with Discord
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default SignIn;

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const session = await getServerAuthSession(ctx);

  if (session) {
    return { redirect: { destination: "/" } };
  }

  return { props: {} };
}
