import Head from "next/head";
import { LogOut } from "lucide-react";
import { signOut, useSession } from "next-auth/react";

import { Button, Avatar, AvatarImage, AvatarFallback } from "@/components/ui";

export { authGssp as getServerSideProps } from "@/server/auth";

const Home = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-4">
            <Avatar className="shadow-xl">
              <AvatarImage src={session?.user.image ?? ""} />
              <AvatarFallback>{session?.user.name}</AvatarFallback>
            </Avatar>
            <Button
              variant="outline"
              className="shadow-xl"
              onClick={() => void signOut({ callbackUrl: "/auth/signin" })}
            >
              <LogOut className="mr-2 h-4 w-4" />
              Sign out
            </Button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
